drop table users cascade constraints;
drop table vaclocations cascade constraints;
drop table testlocations cascade constraints;
drop table vaccination cascade constraints;
drop table vacbooking cascade constraints;
drop table testbooking cascade constraints;
drop table qrcode cascade constraints;


CREATE TABLE USERS (
FNAME VARCHAR2 (30),
LNAME VARCHAR2 (30),
EMAIL VARCHAR2 (100),
PASSWORD VARCHAR2 (100),
DOB DATE,
IDTYPE VARCHAR2 (20),
USERID VARCHAR2 (15),
PHONENO INT,
ADDRESS VARCHAR2 (100),
PRIMARY KEY (EMAIL));

CREATE TABLE VACLOCATIONS (
VACLOCID VARCHAR2 (10),
VACLOCNAME VARCHAR2 (30),
VACTYPEOFLOC VARCHAR2 (30),
VACLOCADDRESS VARCHAR2 (100),
VACSUBURB VARCHAR2 (30),
VACWAITTIME TIME,
VACOPERATIONHOUR VARCHAR2 (200),
PRIMARY KEY (VACLOCID));

CREATE TABLE TESTLOCATIONS (
TESTLOCID VARCHAR2 (10),
TESTLOCNAME VARCHAR2 (30),
TESTTYPEOFLOC VARCHAR2 (30),
TESTLOCADDRESS VARCHAR2 (100),
TESTSUBURB VARCHAR2 (30),
TESTWAITTIME TIME,
TESTOPERATIONHOUR VARCHAR2 (200),
PRIMARY KEY (TESTLOCID));

CREATE TABLE VACCINATION (
VACID VARCHAR2 (5),
VACTYPE VARCHAR2 (30),
PRIMARY KEY (VACID));

CREATE TABLE VACBOOOKING (
VACBOOKID VARCHAR2 (10),
VACLOCID VARCHAR2 (10),
VACDATE DATE,
USERID VARCHAR2 (15),
EMAIL VARCHAR2 (50),
VACTIME VARCHAR2 (6),
VACID VARCHAR2 (5),
PRIMARY KEY (VACBOOKID),
FOREIGN KEY (VACLOCID) REFERENCES VACLOCATIONS,
FOREIGN KEY (VACID) REFERENCES VACCINATION,
FOREIGN KEY (EMAIL) REFERENCES USERS,
FOREIGN KEY (USERID) REFERENCES USERS);

CREATE TABLE TESTBOOOKING (
TESTBOOKID VARCHAR2 (10),
TESTLOCID VARCHAR2 (10),
TESTDATE DATE,
USERID VARCHAR2 (15),
EMAIL VARCHAR2 (50),
TESTTIME VARCHAR2 (6),
PRIMARY KEY (TESTBOOKID),
FOREIGN KEY (TESTLOCID) REFERENCES TESTLOCATIONS,
FOREIGN KEY (EMAIL) REFERENCES USERS,
FOREIGN KEY (USERID) REFERENCES USERS);

CREATE TABLE QRCODE (
QRCODEID VARCHAR2 (10),
QRWEBSITE VARCHAR2 (1000),
QRDESCRIPTION VARCHAR2 (1000),
QRPICTURE BLOB,
PRIMARY KEY (QRCODEID));





